# createUserJob:
#   useHelmHooks: false
#   applyCustomEnv: false
# migrateDatabaseJob:
#   useHelmHooks: false
#   applyCustomEnv: false

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
  labels:
    app: airflow
    component: create-user

migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
  labels:
    app: airflow
    component: run-airflow-migrations

env:
  - name: AIRFLOW__DAG_PROCESSOR__DAG_BUNDLE_CONFIG_LIST
    value: |-
      [
        {
          "name": "sportsflow_dags",
          "classpath": "airflow.providers.git.bundles.git.GitDagBundle",
          "kwargs": {
            "repo_url": "https://github.com/juicebox-platform/sportsflow.git",
            "tracking_ref": "main",
            "subdir": "dags",
            "refresh_interval": 300
          }
        }
      ]

# can eventually use multiple executors concurrently:
# https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/index.html#using-multiple-executors-concurrently
executor: KubernetesExecutor

config:
  kubernetes_executor:
    namespace: airflow
    delete_worker_pods: true
    delete_worker_pods_on_failure: false

# using only k8s executor for now
redis:
  enabled: false
