createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false


dags:
  gitSync:
    enabled: true
    repo: https://github.com/juicebox-platform/sportsflow.git
    rev: HEAD
    branch: main
    subPath: dags

# can eventually use multiple executors concurrently:
# https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/index.html#using-multiple-executors-concurrently
executor: KubernetesExecutor

images:
  airflow:
    # use sportsflow image
    image:
      repository: reecetec/juicebox
      tag: sportsflow-d052e8b
      pullPolicy: Always

# using only k8s executor for now
redis:
  enabled: false
