createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false


dags:
  gitSync:
    enabled: true
    repo: https://github.com/juicebox-platform/sportsflow.git
    rev: HEAD
    branch: main
    subPath: dags

# can eventually use multiple executors concurrently:
# https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/index.html#using-multiple-executors-concurrently
executor: "KubernetesExecutor"

# using only k8s executor for now
redis:
  enabled: false


# for general instance
images:
  airflow:
    repository: reecetec/juicebox
    tag: sportsflow-d052e8b
    pullPolicy: Always

# for workers
config:
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "reecetec/juicebox"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "sportsflow-d052e8b"
