apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickhouse-ingress
  namespace: clickhouse
spec:
  rules:
    - host: clickhouse.juicebox.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: clickhouse-service
                port:
                  number: 8123
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clickhouse-ui-service
                port:
                  number: 5521
