apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: clickhouse-routes
  namespace: clickhouse
spec:
  parentRefs:
  - name: juicebox-gateway
    namespace: istio-system
  hostnames:
  - "clickhouse-api.juicebox.com"
  rules:
  - matches:
    - method: OPTIONS
    backendRefs:
    - name: nginx-cors-service  
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: clickhouse-service  
      port: 8123
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        add:
        - name: Access-Control-Allow-Origin
          value: "https://clickhouse.juicebox.com"
        - name: Access-Control-Allow-Methods
          value: "GET, POST, OPTIONS"
        - name: Access-Control-Allow-Headers
          value: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
        - name: Access-Control-Allow-Credentials
          value: "true"
