apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: clickhouse-api-route
  namespace: clickhouse
spec:
  parentRefs:
  - name: juicebox-gateway
    namespace: istio-system
  hostnames: 
  - "clickhouse-api.juicebox.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: clickhouse-cluster
      port: 8123