apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cors-helper
  namespace: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-cors-helper
  template:
    metadata:
      labels:
        app: nginx-cors-helper
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cors-service
  namespace: clickhouse
spec:
  selector:
    app: nginx-cors-helper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
