apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cors-config
  namespace: clickhouse
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      location / {
        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Allow-Origin' 'https://clickhouse.juicebox.com' always;
          add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
          add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
          add_header 'Access-Control-Allow-Credentials' 'true' always;
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain; charset=utf-8';
          add_header 'Content-Length' 0;
          return 204;
        }
        return 404;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cors-helper
  namespace: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-cors-helper
  template:
    metadata:
      labels:
        app: nginx-cors-helper
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-cors-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cors-service
  namespace: clickhouse
spec:
  selector:
    app: nginx-cors-helper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
